Agent:
  Browser: chrome
  WebDriverManager: true
  Remote: false
  RemoteUrl: ""
  Path: ./drivers/chromedriver.exe
  Headless: false
  Environment: uat

URL:
  CBusOL: https://businessaccessuat.citibank.citigroup.com/cbusol/ang/#/login
  HGJBooking: https://beta-login.hgj.com/login/mail

UserInfo:
  UserName: Cbusol814@163.com
  Password: Q13817759419Q
#Agent:
#  browser: edge
#  driver: ./drivers/msedgedriver.exe
#  headless: true
#  maximum: true
