Agent:
  Browser: chrome
  WebDriverManager: false
  Remote: false
  RemoteUrl: ""
  Path: ./drivers/chromedriver.exe
  Headless: false
  Environment: uat

URL:
  Beta:
    CBusOL: https://businessaccessuat.citibank.citigroup.com/cbusol/ang/#/login
    HGJBooking: https://beta-login.hgj.com/login/mail
  Dev:
    HGJBooking: https://dev-login.hgj.com/login/mail


UserInfo:
  UserName: Cbusol814@163.com
  Password: Q13817759419Q
#Agent:
#  browser: edge
#  driver: ./drivers/msedgedriver.exe
#  headless: true
#  maximum: true
