Agent:
  Browser: chrome
  WebDriverManager: true
  Remote: false
  RemoteUrl: ""
  Path: ./drivers/chromedriver.exe
  Headless: false
  Environment: uat

URL:
  CBusOL: https://businessaccessuat.citibank.citigroup.com/cbusol/ang/#/login


#Agent:
#  browser: edge
#  driver: ./drivers/msedgedriver.exe
#  headless: true
#  maximum: true
