Agent:
  Browser: chrome
  WebDriverManager: false
  Remote: false
  RemoteUrl: ""
  Path: ./drivers/chromedriver.exe
  Headless: false
  Environment: uat

URL:
  Beta:
    CBusOL: https://businessaccessuat.citibank.citigroup.com/cbusol/ang/#/login
    HGJBooking-Email: https://beta-login.hgj.com/login/mail
    HGJBooking-Phone: https://beta-login.hgj.com/
  Dev:
    HGJBooking: https://dev-login.hgj.com/login/mail


EmailReport:
  host: smtp.163.com
  port: 25
  from: "cbusol814@163.com"
  password: "MYUAbcbeD3GKFCfT"
  to: "curtis.yang@yunlsp.com"
  attachment: target/cucumber-reports.html

UserInfo:
  UserName: Cbusol814@163.com
  Password: Q13817759419Q
#Agent:
#  browser: edge
#  driver: ./drivers/msedgedriver.exe
#  headless: true
#  maximum: true
